apiVersion: v1
kind: ReplicationController
metadata:
  name: coffee-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: coffee
    spec:
      nodeSelector:
        role: web
      containers:
      - name: coffee
        image: 10.0.0.100:5000/test/nginx
        #image: nginxdemos/hello
        ports:
        - containerPort: 80
