apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc
  labels:
    app: nginx-ingress
spec:
  replicas: 2
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
#      hostNetwork: true
      nodeSelector:
        lvs: "yes" 
      containers:
      - name: nginx-ingress
#        image: nginxdemos/nginx-ingress:0.3
        image: 10.0.1.1:5000/test/nginx-ingress:0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        # Uncomment the lines below to enable extensive logging and/or customization of
        # NGINX configuration with configmaps
#        args:
#         - -v=3
#         - -nginx-configmaps=default/nginx-config
      - name: vrrp
        image: 10.0.1.1:5000/test/keepalived
        securityContext:
          privileged: true
          capabilities:
            add:
#              - ALL
              - NET_ADMIN
#              - SYS_ADMIN
#              - NET_RAW
        volumeMounts:
        - mountPath: /var/run/netns/node
          name: netns-node
      volumes:
      - name: netns-node
        hostPath:
          path: /proc/1/ns/net

