apiVersion: v1
kind: ReplicationController
metadata:
  name: tea-rc
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: nginxdemos/hello
        ports:
        - containerPort: 80
